# Generated by Django 4.1.6 on 2023-05-07 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dgunotice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagetype',
            fields=[
                ('Pid', models.IntegerField(primary_key=True, serialize=False)),
                ('Nlist', models.CharField(max_length=20)),
                ('Nfixed', models.CharField(max_length=20)),
                ('Nname', models.CharField(max_length=20)),
                ('Nlink', models.CharField(max_length=20)),
                ('Ntime', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='Clink',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='Cname',
            field=models.CharField(max_length=20),
        ),
        migrations.AddField(
            model_name='category',
            name='Pid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dgunotice.pagetype'),
        ),
    ]
