# Generated by Django 4.1.6 on 2023-05-17 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dgunotice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='isSended',
            field=models.BooleanField(default=False),
        ),
    ]
