# Generated by Django 4.1.6 on 2023-05-17 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dgunotice', '0002_notice_issended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='notice_order',
            field=models.CharField(default='1/2/3/4/5/6', max_length=30),
        ),
    ]
