# Generated by Django 4.1.6 on 2023-05-20 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dgunotice', '0002_rename_phone_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
