# Generated by Django 4.1.6 on 2023-05-22 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dgunotice', '0003_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='similar_on',
            field=models.BooleanField(default=True),
        ),
    ]
