# Generated by Django 4.1.6 on 2023-05-17 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dgunotice', '0003_alter_user_notice_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagetype',
            name='Nfixed',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pagetype',
            name='Nlink',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pagetype',
            name='Nlist',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pagetype',
            name='Nname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pagetype',
            name='Ntime',
            field=models.CharField(max_length=50),
        ),
    ]
