# Generated by Django 4.1.6 on 2023-05-22 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dgunotice', '0004_keyword_similar_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='isTrained',
            field=models.BooleanField(default=False),
        ),
    ]
